import Advisor from "@/component/Advisor/Advisor";
import Cabinet from "@/component/Cabinet/Cabinet";
import Heads from "@/component/Heads/Heads";
import About from "@/component/About/About";
import Previous from "@/component/Previous/Previous";
import Layout from "@/component/Layout/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
     <Head>
        <title>Softdesk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@400;700&family=Poppins:wght@300;400;500&display=swap" rel="stylesheet" />

      </Head>
      <main>
        {/*  Layout */}
        <Layout>
          <About />
          <Advisor />
          <Cabinet />
          <Heads />
          <Previous />
        </Layout>
      </main>
    </>
  );
}
